export const ERROR_CODES = ['VALIDATION_ERROR', 'UNAUTHENTICATED', 'FORBIDDEN', 'NOT_FOUND', 'CONFLICT', 'THROTTLED', 'INTERNAL_ERROR', 'INVALID_TRANSITION', 'CUTOFF_PASSED', 'ORDER_INVOICED', 'NO_PRICE_ON_TIER', 'COMBO_QTY_MISMATCH', 'REQUIRED_GROUP_MISSING', 'DOMAIN_TAKEN', 'PUBLIC_DOMAIN_NOT_ALLOWED', 'CUTOFF_NOT_REACHED'] as const;
export type ErrorCode = (typeof ERROR_CODES)[number];
